// TODO: Edit docker-compose.yml

version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - supabase
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app-network

  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "54321:54321" # REST
      - "54322:54322" # Studio
    environment:
      SUPABASE_JWT_SECRET: "your-jwt-secret-at-least-32-characters-long"
      POSTGRES_PASSWORD: "your-database-password"
      POSTGRES_DB: "postgres"
      STUDIO_PORT: "54322"
      API_EXTERNAL_URL: "http://supabase:54321"
      ENABLE_SIGNUP: "true"
    networks:
      - app-network
    volumes:
      - ./supabase/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge
